#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* SCP-L-061

  *アイテム番号*: SCP-L-061

  <br>

  *オブジェクトクラス*: +Euclid+ Neutralized

  <br>

  *特別収容プロトコル*: SCP-L-061無効化手続きの実施，および治安改善の目的から，収容予定はありません。

  <br>

  *説明*: SCP-L-061は蚊の一種です。SCP-L-061は人間が会話を行っている場面に出現し，「くだらないツッコミ」と呼ばれる行為を行った人間に付着し，100ccの血を摂取します。くだらないツッコミとは，本来指摘する必要のないユーモア表現に対する過剰な攻撃行為を指します。

  SCP-L-061の増加率と該当地域の生活満足度には正の相関がありました。関連する調査から，SCP-L-061はくだらないツッコミを行った人間に生じた快楽物質，および攻撃された人間に生じたストレス物質の違いを敏感に感じとり吸血行動に及んでいるらしいことがわかりました。この吸血行動によって他者に対し攻撃的な人間が減少した結果，生活満足度の改善につながったと推測されています。

  SCP-L-061は適切な対話場面では吸血を行わないようです。ここから，SCP-L-061が出現した地域では，プレマックの心の理論をベースにしたコミュニケーション講座，通称SCP-L-061無効化手続きの実施が義務づけられています。

  
  <br>
  <br>
  
  [[https://github.com/jamcha-aa/SCP/blob/master/README.md][目次へ戻る]]
  
  <br>
  <br>
  この文章はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2017 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-sa/4.0/deed][Creative Commons Attribution Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-sa/4.0/deed][file:http://i.creativecommons.org/l/by-sa/3.0/80x15.png]]

